version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "my-redis-commander-container"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis-data:
